spring:
  application:
    name: hiv-care-management

  datasource:
    url: jdbc:mysql://127.0.0.1:3307/hiv_care_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 157953
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    defer-datasource-initialization: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: 
    password: 
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false

  sql:
    init:
      mode: always
      continue-on-error: true

server:
  port: 8080

logging:
  level:
    com.hivcare: DEBUG
    org.springframework.security: DEBUG

app:
  jwt:
    secret: mySecretKey123456789012345678901234567890
    expiration: 86400000 # 24 hours in milliseconds
    refresh-expiration: 604800000 # 7 days

  cors:
    allowed-origins: http://localhost:3000,http://localhost:8080

  file:
    upload-dir: ./uploads
    max-file-size: 10MB

  notification:
    reminder-hours-before: 24
    email-enabled: true
    sms-enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized
api:
  base-url: http://localhost:8080/api
  timeout: 30000

main:
  allow-bean-definition-overriding: true
